apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "virtplc-factory.fullname" . }}-postgresql
  labels:
    {{- include "virtplc-factory.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | default "10Gi" }}
  {{- if .Values.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass }}
  {{- end }}