apiVersion: v1
kind: Secret
metadata:
  name: {{ include "virtplc-factory.postgresql.secretName" . }}
  labels:
    {{- include "virtplc-factory.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}
  password: {{ .Values.postgresql.password | b64enc | quote }}