// Generated by protoc - DO NOT EDIT
package com.virtplc.grpc.plcstream;

public final class PlcStreamServiceGrpc {
    // This would normally be generated by protoc
    // For now, creating minimal implementation

    public static abstract class PlcStreamServiceImplBase {
        public io.grpc.stub.StreamObserver<PlcReading> streamReadings(
                io.grpc.stub.StreamObserver<StreamAck> responseObserver) {
            throw new UnsupportedOperationException("Not implemented");
        }
    }

    public static final class PlcStreamServiceStub {
        // Stub implementation would go here
    }
}