// Generated by protoc - DO NOT EDIT
package com.virtplc.grpc.plcstream;

public final class StreamAck {
    private boolean success;
    private String message;
    private long processedCount;

    // Builder pattern
    public static Builder newBuilder() {
        return new Builder();
    }

    public boolean getSuccess() {
        return success;
    }

    public String getMessage() {
        return message;
    }

    public long getProcessedCount() {
        return processedCount;
    }

    public static class Builder {
        private final StreamAck ack = new StreamAck();

        public Builder setSuccess(boolean success) {
            ack.success = success;
            return this;
        }

        public Builder setMessage(String message) {
            ack.message = message;
            return this;
        }

        public Builder setProcessedCount(long processedCount) {
            ack.processedCount = processedCount;
            return this;
        }

        public StreamAck build() {
            return ack;
        }
    }
}