"""
Client for interacting with the Anthropic Claude API.
"""
import anthropic
import logging
from src.config import settings

class ClaudeClient:
    """
    An asynchronous client for interacting with the Anthropic Claude API.
    """

    def __init__(self):
        """
        Initializes the ClaudeClient, setting up the Anthropic API client
        with the API key from the application settings.
        """
        self.async_client = None
        if settings.claude_api_key:
            self.async_client = anthropic.AsyncAnthropic(api_key=settings.claude_api_key)
        else:
            logger.warning("Claude API key not set - Claude features will be unavailable")

    async def generate_text(self, prompt: str, system_prompt: str = "You are a helpful assistant.") -> str:
        """
        Generates text asynchronously using the Claude API based on a given prompt and system prompt.

        Args:
            prompt: The user's prompt.
            system_prompt: The system prompt to guide the model's behavior.

        Returns:
            The text generated by the Claude model.
        """
        if not self.async_client:
            raise ValueError("Claude API key is not configured. Claude features are unavailable.")
        
        message = await self.async_client.messages.create(
            model=settings.claude_model,
            max_tokens=settings.claude_max_tokens,
            system=system_prompt,
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
        )
        return message.content[0].text

    async def stream_text(self, prompt: str, system_prompt: str = "You are a helpful assistant."):
        """
        Generates and streams text asynchronously using the Claude API.

        Args:
            prompt: The user's prompt.
            system_prompt: The system prompt to guide the model's behavior.
        
        Yields:
            Chunks of text from the Claude API.
        """
        if not self.async_client:
            raise ValueError("Claude API key is not configured. Claude features are unavailable.")
        
        async with self.async_client.messages.stream(
            model=settings.claude_model,
            max_tokens=settings.claude_max_tokens,
            system=system_prompt,
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
        ) as stream:
            async for text in stream.text_stream:
                yield text

# Global Claude client instance
claude_client = ClaudeClient()
