// Generated by protoc - DO NOT EDIT
package com.virtplc.grpc.plcstream;

import com.google.protobuf.Timestamp;

public final class PlcReading {
    private String tenantId;
    private String manufacturerId;
    private String factoryId;
    private String plcId;
    private String sensorId;
    private Timestamp timestamp;
    private double value;
    private String unit;
    private String metadata;

    // Builder pattern
    public static Builder newBuilder() {
        return new Builder();
    }

    public String getTenantId() { return tenantId; }
    public String getManufacturerId() { return manufacturerId; }
    public String getFactoryId() { return factoryId; }
    public String getPlcId() { return plcId; }
    public String getSensorId() { return sensorId; }
    public Timestamp getTimestamp() { return timestamp; }
    public double getValue() { return value; }
    public String getUnit() { return unit; }
    public String getMetadata() { return metadata; }

    public static class Builder {
        private final PlcReading reading = new PlcReading();

        public Builder setTenantId(String tenantId) { reading.tenantId = tenantId; return this; }
        public Builder setManufacturerId(String manufacturerId) { reading.manufacturerId = manufacturerId; return this; }
        public Builder setFactoryId(String factoryId) { reading.factoryId = factoryId; return this; }
        public Builder setPlcId(String plcId) { reading.plcId = plcId; return this; }
        public Builder setSensorId(String sensorId) { reading.sensorId = sensorId; return this; }
        public Builder setTimestamp(Timestamp timestamp) { reading.timestamp = timestamp; return this; }
        public Builder setValue(double value) { reading.value = value; return this; }
        public Builder setUnit(String unit) { reading.unit = unit; return this; }
        public Builder setMetadata(String metadata) { reading.metadata = metadata; return this; }

        public PlcReading build() { return reading; }
    }
}